
// Currency constants start
export const CURRENCY_TYPES = {
  GOLD_COIN: 'gold-coin',
  SWEEP_COIN: 'sweep-coin'
}
// Currency constants

export const SWEEPS_COINS = {
  GC: 'GC',
  BSC: 'BSC',
  PSC: 'PSC',
  RSC: 'RSC'
}

export const SWEEPS_COINS_ID = {
  GC: '1'
}

export const LEDGER_TRANSACTION_TYPE = {
  CASINO: 'casino',
  STANDARD: 'standard',
  WITHDRAWAL: 'withdrawal'
}

export const AMOE_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected'
}

// Ledger constants start
export const LEDGER_TYPES = {
  DEBIT: 'debit',
  CREDIT: 'credit'
}

export const LEDGER_PURPOSE = {
  DEPOSIT: 'Deposit',
  WITHDRAW: 'Withdraw',
  WINNINGS: 'Winnings',
  PURCHASE: 'Purchase',
  REDEEM: 'Redeem',
  AMOE: 'AmoEntry',
  COMMISSION: 'Commission',
  CASINO_BET: 'CasinoBet',
  CASINO_WIN: 'CasinoWin',
  CASINO_REFUND: 'CasinoRefund',
  CASINO_BET_ROLLBACK: 'CasinoBetRollback',
  CASINO_WIN_ROLLBACK: 'CasinoWinRollback',
  SPORTSBOOK_BET: 'SportsbookBet',
  SPORTSBOOK_WIN: 'SportsbookWin',
  SPORTSBOOK_REFUND: 'SportsbookRefund',
  SPORTSBOOK_CASHOUT: 'SportsbookCashout',
  SPORTSBOOK_EXCHANGE_BET: 'SportsbookExchangeBet',
  SPORTSBOOK_EXCHANGE_WIN: 'SportsbookExchangeWin',
  SPORTSBOOK_EXCHANGE_REFUND: 'SportsbookExchangeRefund',
  SPORTSBOOK_EXCHANGE_CASHOUT: 'SportsbookExchangeCashout',
  SB_RESETTLEMENT_LOST_TO_REFUND: 'ResettlementLostToRefund', // credit
  SB_RESETTLEMENT_LOST_TO_WIN: 'ResettlementLostToWin', // credit
  SB_RESETTLEMENT_OPEN_TO_WIN: 'ResettlementOpenToWin', // credit
  SB_RESETTLEMENT_WIN_TO_OPEN: 'ResettlementWinToOpen', // debit
  SB_RESETTLEMENT_WON_TO_LOST: 'ResettlementWinToLost', // debit
  SB_RESETTLEMENT_REFUND_TO_LOST: 'ResettlementRefundToLost', // debit
  SB_RESETTLEMENT_REFUND_TO_OPEN: 'ResettlementRefundToOpen', // debit
  SB_RESETTLEMENT_OPEN_TO_REFUND: 'ResettlementOpenToRefund', // credit
  TOURNAMENT_ENROLL: 'TournamentEnroll', // debit
  TOURNAMENT_WIN: 'TournamentWin', // credit
  TOURNAMENT_CANCEL: 'TournamentCancel', // credit
  TOURNAMENT_REBUY: 'TournamentRebuy', // credit
  REFERRAL_DEPOSIT: 'ReferralDeposit', // credit
  BONUS_ZEROEDOUT: 'BonusZeroedout',
  BONUS_LAPSED: 'BonusLapsed',
  BONUS_CASHED: 'BonusCashed',
  BONUS_DEPOSIT: 'BonusDeposit'
}

export const LEDGER_RULES = {
  [LEDGER_PURPOSE.DEPOSIT]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.WITHDRAW]: LEDGER_TYPES.DEBIT,
  [LEDGER_PURPOSE.PURCHASE]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.AMOE]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.REDEEM]: LEDGER_TYPES.DEBIT,
  [LEDGER_PURPOSE.CASINO_BET]: LEDGER_TYPES.DEBIT,
  [LEDGER_PURPOSE.CASINO_WIN]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.COMMISSION]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.CASINO_REFUND]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.SPORTSBOOK_BET]: LEDGER_TYPES.DEBIT,
  [LEDGER_PURPOSE.SPORTSBOOK_WIN]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.SPORTSBOOK_REFUND]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.SPORTSBOOK_CASHOUT]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.SPORTSBOOK_EXCHANGE_BET]: LEDGER_TYPES.DEBIT,
  [LEDGER_PURPOSE.SPORTSBOOK_EXCHANGE_WIN]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.SPORTSBOOK_EXCHANGE_REFUND]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.SPORTSBOOK_EXCHANGE_CASHOUT]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.SB_RESETTLEMENT_LOST_TO_REFUND]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.SB_RESETTLEMENT_LOST_TO_WIN]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.SB_RESETTLEMENT_OPEN_TO_WIN]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.SB_RESETTLEMENT_WIN_TO_OPEN]: LEDGER_TYPES.DEBIT,
  [LEDGER_PURPOSE.SB_RESETTLEMENT_WON_TO_LOST]: LEDGER_TYPES.DEBIT,
  [LEDGER_PURPOSE.SB_RESETTLEMENT_REFUND_TO_LOST]: LEDGER_TYPES.DEBIT,
  [LEDGER_PURPOSE.SB_RESETTLEMENT_REFUND_TO_OPEN]: LEDGER_TYPES.DEBIT,
  [LEDGER_PURPOSE.SB_RESETTLEMENT_OPEN_TO_REFUND]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.TOURNAMENT_WIN]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.TOURNAMENT_CANCEL]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.TOURNAMENT_ENROLL]: LEDGER_TYPES.DEBIT,
  [LEDGER_PURPOSE.TOURNAMENT_REBUY]: LEDGER_TYPES.DEBIT,
  [LEDGER_PURPOSE.REFERRAL_DEPOSIT]: LEDGER_TYPES.CREDIT,
  [LEDGER_PURPOSE.BONUS_ZEROEDOUT]: LEDGER_TYPES.DEBIT,
  [LEDGER_PURPOSE.BONUS_LAPSED]: LEDGER_TYPES.DEBIT,
  [LEDGER_PURPOSE.BONUS_CASHED]: LEDGER_TYPES.CREDIT
}
// Ledger constants end

// Transaction constants start
export const TRANSACTION_STATUS = {
  PENDING: 'pending',
  COMPLETED: 'completed'
}
// Transaction constants end

// Document constants start
export const DOCUMENT_STATUS_TYPES = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  REQUESTED: 'requested'
}
// Document constants end

// Setting constants start
export const SETTING_DATA_TYPES = {
  STRING: 'string',
  NUMBER: 'number',
  BOOLEAN: 'boolean',
  PERCENTAGE: 'percentage',
  JSON: 'json'
}
// Setting constants end

// User constants start
export const USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES = {
  SELF_EXCLUSION: 'self_exclusion',
  DAILY_BET_LIMIT: 'daily_bet_limit',
  WEEKLY_BET_LIMIT: 'weekly_bet_limit',
  MONTHLY_BET_LIMIT: 'monthly_bet_limit',
  DAILY_LOSS_LIMIT: 'daily_loss_limit',
  WEEKLY_LOSS_LIMIT: 'weekly_loss_limit',
  MONTHLY_LOSS_LIMIT: 'monthly_loss_limit',
  DAILY_DEPOSIT_LIMIT: 'daily_deposit_limit',
  WEEKLY_DEPOSIT_LIMIT: 'weekly_deposit_limit',
  MONTHLY_DEPOSIT_LIMIT: 'monthly_deposit_limit',
  DAILY_PLAY_LIMIT: 'daily_play_limit',
  WEEKLY_PLAY_LIMIT: 'weekly_play_limit',
  MONTHLY_PLAY_LIMIT: 'monthly_play_limit',
  DAILY_PURCHASE_LIMIT: 'daily_purchase_limit',
  WEEKLY_PURCHASE_LIMIT: 'weekly_purchase_limit',
  MONTHLY_PURCHASE_LIMIT: 'monthly_purchase_limit',
  TEMPORARY_DISABLED: 'temporary_disabled'
}

export const SELF_EXCLUSION_TYPES = {
  PERMANENT: 'permanent',
  TEMPORARY: 'temporary'
}

export const USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES = {
  ENUM: 'enum',
  STRING: 'string',
  NUMBER: 'number',
  BOOLEAN: 'boolean',
  INTEGER: 'integer',
  PERCENTAGE: 'percentage'
}

export const RESPONSIBLE_GAMBLING_DATA_TYPE_MAPPING = {
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.SELF_EXCLUSION]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.ENUM,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.DAILY_PLAY_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.INTEGER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.WEEKLY_PLAY_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.INTEGER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.MONTHLY_PLAY_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.INTEGER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.DAILY_PURCHASE_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.NUMBER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.WEEKLY_PURCHASE_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.NUMBER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.MONTHLY_PURCHASE_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.NUMBER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.DAILY_BET_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.INTEGER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.WEEKLY_BET_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.INTEGER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.MONTHLY_BET_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.INTEGER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.DAILY_DEPOSIT_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.NUMBER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.WEEKLY_DEPOSIT_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.NUMBER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.MONTHLY_DEPOSIT_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.NUMBER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.DAILY_LOSS_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.NUMBER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.MONTHLY_LOSS_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.NUMBER,
  [USER_RESPONSIBLE_GAMBLING_LIMIT_TYPES.WEEKLY_LOSS_LIMIT]: USER_RESPONSIBLE_GAMBLING_LIMIT_DATA_TYPES.NUMBER
}

export const USER_GENDER = {
  MALE: 'male',
  FEMALE: 'female',
  UNKNOWN: 'unknown'
}
// User constants end
export const USER_ROLE = {
  ADMIN: 'admin',
  USER: 'user'
}
// Withdrawal constants start
export const WITHDRAWAL_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  CONFIRMED: 'confirmed',
  SUCCESS: 'success',
  FAILED: 'failed'
}

export const WITHDRAWAL_TYPES = {
  BANK: 'bank',
  CRTPTO: 'crypto'
}
// Withdrawal constants end

// Email template constants start
export const EMAIL_TEMPLATE_EVENT_TYPES = {
  WELCOME: 'welcome',
  ACTIVE_USER: 'active_user',
  INACTIVE_USER: 'inactive_user',
  FORGOT_PASSWORD: 'forgot_password',
  RESET_PASSWORD: 'reset_password',
  EMAIL_VERIFICATION: 'email_verification',
  DOCUMENT_REJECTED: 'document_rejected',
  DOCUMENT_REMINDER: 'document_reminder',
  DOCUMENT_RECEIVED: 'document_received',
  DOCUMENT_VERIFIED: 'document_verified',
  DOCUMENT_REQUESTED: 'document_requested',
  KYC_ACTIVATED: 'kyc_activated',
  KYC_DEACTIVATED: 'kyc_deactivated',
  WITHDRAW_PROCESSED: 'withdraw_processed',
  WITHDRAW_REQUEST_RECEIVED: 'withdraw_request_received',
  WITHDRAW_REQUEST_APPROVED: 'withdraw_request_approved',
  DEPOSIT_FAILED: 'deposit_failed',
  DEPOSIT_SUCCESS: 'deposit_success',
  GAMBLING_REGISTRATION: 'gambling_registration',
  JOINING_BONUS: 'joining_bonus',
  PASSWORD_UPDATED: 'password_updated'
}
// Email template constants end

// Banner constants start
export const BANNER_TYPES = {
  HOME: 'home',
  CASINO: 'casino',
  LOYALITY: 'loyality',
  PROMOTIONS: 'promotions',
  SPORTSBOOK: 'sportsbook'
}
// Banner constants end

// AMOUNT_TYPES
export const AMOUNT_TYPES = {
  CASH: 'cash',
  BONUS: 'bonus',
  BONUS_PLUS_CASH: 'bonus_plus_cash'
}
// QUERY_STATUS constants start
export const QUERY_STATUS = {
  PENDING: 'pending',
  ACTIVE: 'active',
  RESOLVED: 'resolved',
  REOPENED: 'reopened'
}
// QUERY_STATUS constants end

// PROVIDER_TYPE constants start
export const PROVIDER_TYPE = {
  PAYMENT: 'payment',
  CASINO: 'casino',
  CRM: 'crm',
  OTHER: 'other'
}
// PROVIDER_TYPE constants end

export const PLAYER_MANAGEMENT_KYC_STATUS = {
  UPLOAD_ALL_REQUIRED_DOCUMENTS: 'Upload All Required Documents'
}

export const REPORT_TYPES = {
  BANKING_TRANSACTIONS: 'banking_transactions',
  CASINO_TRANSACTION: 'casino_transactions',
  GAME_REPORTS: 'game_reports',
  PLAYER_PERFORMANCE: 'player_performance'
}

export const COLUMNS_TO_EXCLUDE = {
  [REPORT_TYPES.BANKING_TRANSACTIONS]: ['user.userTags.id', 'user.userTags.tagId', 'user.userTags.userId'],
  [REPORT_TYPES.CASINO_TRANSACTION]: ['user.userTags.id', 'user.userTags.tagId', 'user.userTags.userId']
}
